spring:
  application:
    name: AdiPharma
  datasource:
    url: jdbc:postgresql://localhost:5432/adi_pharma
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
